In [21]:
import numpy as np
arr = np.array([[[10, 20, 30, 40], [50, 60, 70, 80]], [[12, 13, 14, 15], [16, 17, 18, 19]]])
print(arr)
print(type(arr))

[[[10 20 30 40]
  [50 60 70 80]]

 [[12 13 14 15]
  [16 17 18 19]]]
<class 'numpy.ndarray'>


In [30]:
a = np.array([[11, 22, 33, ], [10, 20, 30]])
print(a)
b = 4
print(b)
c = a+b
print('\n',c)
result = np.add(a, b)
result

[[11 22 33]
 [10 20 30]]
4

 [[15 26 37]
 [14 24 34]]


array([[15, 26, 37],
       [14, 24, 34]])

In [25]:
print(a.shape)
A = a.reshape(3,2)
print(A)
print(A.shape)
B = np.concatenate((a, a))
print(B)

(2, 3)
[[11 22]
 [33 10]
 [20 30]]
(3, 2)
[[11 22 33]
 [10 20 30]
 [11 22 33]
 [10 20 30]]


In [31]:
str = "Hello How are you"
print(str)
a = np.char.replace(str, 'Hello', 'Hi')
print(a)
b = np.char.lower(a)
print("\n\n",b)

Hello How are you
Hi How are you


 hi how are you


In [38]:
a = np.array([[30,40,60],[50,70,91]])
b = np.array([[10,20,30], [30,20,10]])
result = np.subtract(a,b)
print(result)

B = np.mod(a,b)
print("\n",B)

[[20 20 30]
 [20 50 81]]

 [[ 0  0  0]
 [20 10  1]]


In [48]:
Y = np.array([[[11,22,33,],[44,55,66]],[[77,88,99],[100,111,122]]])
print(Y)
print("\n", Y[1, 1, 0])
print("\n",Y[1,1,-2])
print(Y[0:1])

[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [100 111 122]]]

 100

 111
[[[11 22 33]
  [44 55 66]]]


In [50]:
X = np.array([8,7,6,5,4,3,2,1])
print(X[1:6:3])
Y = np.array([1])

[7 4]


In [54]:
import random
np.random.randint(1,50,(2,2))

array([[36, 34],
       [ 6, 33]])