In [3]:
import numpy as np
first_numpy = np.array([1,2,3,4])
print(first_numpy)

[1 2 3 4]


In [8]:
numpy_zeros = np.zeros((3,3))
print(numpy_zeros)
numpy_ones = np.ones((4,4))
print("\n", numpy_ones)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
empty_array = np.empty((2,3))
empty_array

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.24611470e-306, 3.56174938e-317, 1.39067116e-308]])

In [14]:
np_arange = np.arange(12)
print(np_arange)
rshape = np_arange.reshape(3,4)
print("\n", rshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
np_linespce = np.linspace(1,6,5)
print(np_linespce)

[1.   2.25 3.5  4.75 6.  ]


In [26]:
oneD_array = np.arange(16)
print(oneD_array)
twoD_array = oneD_array.reshape(4,4)
print("\n", twoD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [31]:
np.array(24)

array(24)

In [33]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [37]:
np.array([[1,2,3,4],[9,8,7,6]])

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [42]:
fourD_arr = np.array([[[1,2,3],[4,5,6]],[[9,8,7],[4,5,6]],[[4,5,6],[1,5,9]]])
print(fourD_arr.shape)

(3, 2, 3)


In [48]:
numpy_arr = np.array([x for x in range(1,10)])
print(numpy_arr)
print("\n", numpy_arr.reshape(3,3))
numpy_arr.reshape(3,3)

[1 2 3 4 5 6 7 8 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
numpy_arr = np.array([x for x in range(1,13)])
print(numpy_arr)
numpy_arr.reshape(2,2,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [53]:
numpy_arr.reshape(2,2,-1) #the -1 auto calculates last dim to fit number of elements

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
numpy_arr = numpy_arr.reshape(-1) #-1 flattens array
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
A = np.array([[1, 2,3], [2,2,3]])
B = np.array([4,5,6])
np.add(A,B) #adds array B to each row of array A

array([[5, 7, 9],
       [6, 7, 9]])

In [62]:
np.subtract(B,A) #can do same with multiply, div, square

array([[3, 3, 3],
       [2, 3, 3]])

In [64]:
x = np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.where(x%2 == 0, 'even', 'odd') #one line if else statment

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [68]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [71]:
arr = np.array([[4,3,2], [10,1,0], [5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [78]:
print(np.amin(arr)) #min value in arr
print(np.amin(arr, axis=0)) #min value in each colum
print(np.amin(arr, axis=1)) #min value in each row, 
print(np.max(arr)) #max of arr
print(np.amax(arr, axis=0)) #max in col
print(np.amax(arr, axis=1)) #max in rows, simular median, mean, SD, var


0
[4 1 0]
[2 0 5]
24
[10  8 24]
[ 4 10 24]


In [80]:
np.percentile(arr, 50)

4.0

In [83]:
deg = np.array([0, 30, 45, 60, 90])
sin_rad = np.sin(deg*np.pi/180) #convert deg to rad and eval sin(x), same tan, cos
sin_rad


array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [86]:
x = np.array([1.2, 3.174, 75.75, 1.25])
np.floor(x) #round down
np.ceil(x) #row up  

array([ 2.,  4., 76.,  2.])

In [91]:
array_3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
array_3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [1]:
print(array_3d[0,1,2]) #array_3d[matrix, row, col]

NameError: name 'array_3d' is not defined

In [1]:
from math import sqrt, sin
A = 16
B = 3.14
print(sqrt(A))
print(sin(B))

4.0
0.0015926529164868282
